### ISSUE TITLE
Consider releasing in vx.y.z form for tools like Renovate to better diff version changes

### ISSUE THREAD

**Issue by bfqrst** [awslabs/mountpoint-s3#455]
### Tell us more about this new feature.

This gem couldn't hit GA at a better time, so thanks for that! The title is quite self explanatory, so if it isn't too much hassle and doesn't conflict with internal releasing schemes, I'd rather skip the regex magic to extract the semver version from the release.
I've included two examples down below...

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/releases/tag/v1.21.0
https://github.com/kubernetes-sigs/aws-efs-csi-driver/releases/tag/v1.5.9

Cheers and THX

**Comment by jamesbornholt** [comment]
Thanks for the suggestion. We're using the `mountpoint-s3-1.0.0` style of tagging because there's actually four different Rust crates maintained in this repo, each with independent releases. But `mount-s3` is the "main" one, so perhaps we should use the `v1.0.0` style for it instead. We'll look into this the next time we do a release.

**Comment by bfqrst** [comment]
Amazing, thank you!

**Comment by jamesbornholt** [comment]
The new 1.0.1 release is tagged with `v1.0.1` in addition to `mountpoint-s3-1.0.1`, and we'll do that going forward too. Thanks!
