### ISSUE TITLE
Warnings when unzipping a file

### ISSUE THREAD

**Issue by robertd** [awslabs/mountpoint-s3#456]
### Mountpoint for Amazon S3 version

1.0

### AWS Region

us-east-1

### Describe the running environment

Running in an EC2 instance using AL2, mounting S3 bucket in the same account.

### What happened?

I got bot bunch of warnings when unzipping a file.

> warning:  cannot set modif./access times for 015895550010_01_003/GIS_FILES/
          Operation not permitted

**Comment by robertd** [comment]
<img width="1159" alt="image" src="https://github.com/awslabs/mountpoint-s3/assets/31543/7f78500e-cc9c-4446-ab81-718ea1397efd">

**Comment by jamesbornholt** [comment]
Thanks for the report! I believe this is expected behavior: `unzip` is trying to preserve permissions and metadata for the files it extracts, but Mountpoint [doesn't allow setting permissions or metadata](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#permissions-and-metadata) on files (because S3 can't persist them). You can pass the `-DDD` flag to `unzip` to disable preserving permissions/metadata, which should silence the warnings.

**Comment by robertd** [comment]
Thanks so much @jamesbornholt.
