### ISSUE TITLE
No signing credentials found

### ISSUE THREAD

**Issue by jchorl** [awslabs/mountpoint-s3#493]
### Mountpoint for Amazon S3 version

6103a2f3ca90a603bec34d4d064099b13ce3bfe6

### Describe the running environment

EC2, using instance IAM role

### What happened?

I see in logs:
```
Error: Failed to create S3 client
Caused by:
 0: initial ListObjectsV2 failed for bucket <bucket> in region us-west-2
 1: Client error
 2: No signing credentials found
```

For context, I see these errors crop up on multitenant hosts running a variety of workloads, so this can be caused by other processes misbehaving or many concurrent mountpoint processes.

This does work in the vast majority of cases, so I believe the credentials/IAM are configured correctly.

My guess is that we're hammering IMDS to get instance creds and one of those calls is failing, netting the client unable to sign s3 requests.

I don't know how to prove this hypothesis.

First question: have you seen something like this before? Do you have ideas to test this hypothesis? I.e. I'm not sure how hard it'd be to rig the client to fetch signing credentials repeatedly and see if this error occurs. Possibly relevant: https://github.com/awslabs/mountpoint-s3/pull/447

Next question - what to do about it.

I've seen this env var floating around: `AWS_METADATA_SERVICE_NUM_ATTEMPTS`. However, grepping through the rust aws sdk, I couldn't find references to it, so I'm not sure the rust client respects it.

Then I had a look through mountpoint code, and it seems there is a separate `c` auth client, with its own retry config.

So I'm a bit stuck on how to make progress here. It's very infrequent, so it's tough to capture any sort of logs or data.

Any insights appreciated!

### Relevant log output

```shell
Error: Failed to create S3 client
Caused by:
 0: initial ListObjectsV2 failed for bucket <bucket> in region us-west-2
 1: Client error
 2: No signing credentials found
```

**Comment by jamesbornholt** [comment]
I haven't seen this one before, but I agree from what you've seen that a good hypothesis is [IMDS throttling](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#instancedata-throttling) if you're using instance profile credentials and running many concurrent mounts per instance. It looks like we don't override the default IMDS client's [retry policy](https://github.com/awslabs/aws-c-auth/blob/main/source/aws_imds_client.c#L185), which is a [single retry](https://github.com/awslabs/aws-c-auth/blob/8d739c5c8c37a894d1aabd09dadf112d643d5237/source/aws_imds_client.c#L31C1-L31C50) (two attempts).

So a thing you could try is to modify that policy. A hacky way would be to just change that `IMDS_DEFAULT_RETRIES` constant in the C code and recompile. It would be a bit of work to do it the "right way", because there's currently no way to [pass retry options to the IMDS credentials provider](https://github.com/awslabs/aws-c-auth/blob/8d739c5c8c37a894d1aabd09dadf112d643d5237/source/credentials_provider_imds.c#L83). But we could figure it out if this turns out to be the issue.

As far as I can figure out, `AWS_METADATA_SERVICE_NUM_ATTEMPTS` is specific to boto3, but it certainly seems reasonable for other SDKs to support it too. That could be a way we make this work, by making the IMDS credentials provider or the IMDS client read that variable.

**Comment by jchorl** [comment]
James, thanks for the thoughtful response and informative links.

This enabled me to reproduce and fix the issue. Here's a quick writeup, with some testing programs: https://gist.github.com/jchorl/da752bec23ea2d3287f103778a863f84

I can just override these vars at build time. There's also some other avenues I can try, so not urgent here.

Anyway, thanks for the help. I'll close, and place a vote for making retry behaviour configurable at some point.

**Comment by ps-spark** [comment]
Hi @jchorl , hi @jamesbornholt,

I'm also experiencing this problem running in a Docker container (AWS EMR image). The AWS profiles are configured in the ~/.aws folder and AWS CLI is working.

```bash
mount-s3 scene-intel-rosbag-ingestion-raw-340752333339 /mnt/scene-intel-rosbag-ingestion --profile jbdata-admin
Error: Failed to create S3 client

Caused by:
    0: initial ListObjectsV2 failed for bucket scene-intel-rosbag-ingestion-raw-340752333339 in region eu-central-1
    1: Client error
    2: No signing credentials found
Error: Failed to create mount process
```

AWS CLI
```bash
aws s3 ls --profile jbdata-admin
2024-09-11 06:12:47 addf-demo-artifacts-bucket-fd97bda4-8abb746dd2b06be274a04b443
2024-09-11 06:12:43 addf-demo-curated-bucket-fd97bda4-8abb746dd2b06be274a04b443e1
...
```

Any idea?
