### ISSUE TITLE
Supporting renaming of a file

### ISSUE THREAD

**Issue by lciaan** [awslabs/mountpoint-s3#506]
### Tell us more about this new feature.

Feature that allows a customer to perform rename or move operations by S3 mountpoint

**Comment by passaro** [comment]
Hi. Thanks for your feedback. Since move/rename operations cannot be implemented efficiently against S3's object APIs, the [Mountpoint approach](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#behavior-tenets) is to not support them. I am closing this issue for now.

**Comment by Gentoli** [comment]
aws cli's s3 mv command can copy the file without download/uploading. copying the implementation of that will be way more efficient than doing a local `cp`

**Comment by treksler** [comment]
this is ridiculous. I am trying to use mountpoint s3 csi driver as gitlab runner cache. it needs to perform one!!! rename operation per run.

```FATAL: rename ../../../../cache/my-project/default-non_protected/archive_912314317 ../../../../cache/my-project/default-non_protected/cache.zip: function not implemented ```

can't be done because of daddy knows best attitude. at the very least there needs to be a --allow-rename flag like there is a --allow-delete flag. maybe there needs to be a limit on rename operations that is also configurable.

i can understand the need to prevent someone renaming a folder with a million objects in it, but there are many use cases where not having rename available makes the whole drive less than useless

**Comment by mdnadm** [comment]
need rename guys !

**Comment by project0** [comment]
same, without it is supper limited in use case.

**Comment by zeddit** [comment]
+1, add a feature only allowing rename just one object would help a lot!

**Comment by auguzsto** [comment]
+1

**Comment by erny** [comment]
+1
