### ISSUE TITLE
Saw the setattr just set on the inode in memory, not to s3 store

### ISSUE THREAD

**Issue by inevity** [awslabs/mountpoint-s3#576]
What consideration for this decision?

**Comment by monthonk** [comment]
Hi, we actually did not plan to support `setattr` operation since ListObjectV2 doesn’t allow us to read those attributes back efficiently. To get them, we have to iterate over each file/directory which is incredibly slow. The reason we allow to set them in memory is because some applications like touch rely on this operation to set access time of the file.

Anyway, we think there is a bug with this operation since it just silently ignore other attributes that we don’t support like the permissions bits. I have opened https://github.com/awslabs/mountpoint-s3/issues/600 for that.

**Comment by dannycjones** [comment]
Closing this. #600 is opened to discuss how this behavior should be fixed moving forward.
