### ISSUE TITLE
Double `touch` errors

### ISSUE THREAD

**Issue by jchorl** [awslabs/mountpoint-s3#729]
### Mountpoint for Amazon S3 version

778aad3ee2379c270c3ff9979e86415f956cb1c5

### AWS Region

us-west-2

### Describe the running environment

Built with `cargo build --release`. Running on ubuntu 22.04. Local machine, not on AWS.

### Mountpoint options

```shell
mount-s3 --region us-west-2 --allow-delete --allow-overwrite --foreground --prefix /joshtest/2024-02-02/foo/ my-bucket mnt
```

### What happened?

In one terminal:
```
mount-s3 --region us-west-2 --allow-delete --allow-overwrite --foreground --prefix /joshtest/2024-02-02/foo/ my-bucket mnt
```

Another terminal:
```
$ touch mnt/bar
$ echo $?
0
```

So far so good!

Quit mountpoint. Start it up again, same command:
```
mount-s3 --region us-west-2 --allow-delete --allow-overwrite --foreground --prefix /joshtest/2024-02-02/foo/ my-bucket mnt
```

Another terminal:
```
$ echo bing > mnt/bar
$ echo $?
0
```

Still good!

Now for another `touch` on an existing file. Again we boot up mountpoint:
```
mount-s3 --region us-west-2 --allow-delete --allow-overwrite --foreground --prefix /joshtest/2024-02-02/foo/ my-bucket mnt
```

```
$ touch mnt/bar
touch: setting times of 'mnt/bar': Operation not permitted
$ echo $?
1
```

^^ this failed, exited code 1

I understand that setting attrs doesn't make much sense. But when you `touch` a file, it's annoying to need to check if it exists already or not.

Curious what would be involved in making this work.

**Comment by jamesbornholt** [comment]
This isn't ideal, but it is our intended behavior. Our thinking was that we don't want to lie about `touch` successfully persisting the modification time update back to S3, which it can't do. It quickly becomes a slippery slope of "what mutations are we allowed to lie about" so we decided to just draw a bright line. (It's mentioned tangentially in #391, which is when we made `touch` work properly on new files because there we actually can persist the update.)

I'm hoping it's not something that's going to actively block you, but if it is please let us know!

**Comment by jchorl** [comment]
Thanks for the response - the reasoning makes sense.

It does [seem](https://stackoverflow.com/a/42729819) the modification date is immutable. I believe you could replicate `touch` by writing empty-file if it doesn't exist, or copying the file to itself if it does. I'm not sure if the posix spec gives you enough details to know to do this.

Anyway, it's not a huge deal. I build our own mountpoint binary anyway, so I just patch it to no-op touches when the file exists (shouldn't be upstreamed, but fine for my use-case). This is the only patch that I carry but it doesn't cause much pain.

Thanks as always for the response.
