### ISSUE TITLE
`stat` call for path triggers two requests (one List and one Head) with enabled cache

### ISSUE THREAD

**Issue by mhnap** [awslabs/mountpoint-s3#777]
### Mountpoint for Amazon S3 version

mount-s3 1.4.0

### AWS Region

us-east-2

### Describe the running environment

Running in EC2 on Ubuntu 22.04.3 LTS using instance profile credentials against an S3 Bucket in the same account.

### Mountpoint options

```shell
mount-s3 mhnap-bucket /media/mount-s3 --read-only --log-directory=/tmp/mount-s3/logs --debug --debug-crt --log-metrics --cache /tmp/mount-s3 --metadata-ttl 1000
```

### What happened?

This issue is similar to https://github.com/awslabs/mountpoint-s3/issues/770 that I previously created, but here I enabled metadata caching.

I have created `dir1/dir2/dir3/` directory hierarchy with hundred `file{1..100}` files inside `dir3` and uploaded `dir1` to my newly created `mhnap-bucket`.

After, I mounted this bucket using the `mount-s3` command and called `stat` one time for each one of hundred `/media/mount-s3/dir1/dir2/dir3/file{1..100}` files.

With metadata caching enabled I see two requests (one List and one Head) for each file and for `dir1/`, `dir1/dir2/` and `dir1/dir2/dir3/`. From https://github.com/awslabs/mountpoint-s3/issues/770 answer I know why there are requests for `dir1/`, `dir1/dir2/` and `dir1/dir2/dir3/`. But I'm curious about the number of requests per path. 

I would be grateful to know whether it's also expected behavior to see one List and one Head request per each path.

I found https://github.com/awslabs/mountpoint-s3/issues/12 issue that seems similar, but I'm not sure whether it's the same.

Cannot paste logs, so uploaded them here: [mountpoint-s3-2024-02-22T12-33-06Z.log](https://github.com/awslabs/mountpoint-s3/files/14374573/mountpoint-s3-2024-02-22T12-33-06Z.log)

**Comment by passaro** [comment]
This seems in line with expected behavior: one pair of requests for each directory in the hierarchy and one pair for each file.

As mentioned in #12, Mountpoint needs to make a pair of requests (Head + List) for each entry in order to establish whether to map it to a file or a directory (see docs [here](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#directories)).

By using the `--cache` and `--metadata-ttl` options, you are allowing Mountpoint to skip repeated requests for each entry (within the set TTL), so in your test you only see one pair of requests for each `dir`. If you called `stat` multiple times on the same files, you should not see any additional requests.
