### ISSUE TITLE
Add support for environment variables to configure the mountpoint-s3-cli

### ISSUE THREAD

**Issue by kimminw00** [awslabs/mountpoint-s3#948]
### Tell us more about this new feature.

I tried to read data stored in s3 with [s3-connector-for-pytorch.](https://github.com/awslabs/s3-connector-for-pytorch) 
But our storage provider does not support virtual style hosted bucket.
So we have to use [`--force-path-style` CLI option](https://github.com/awslabs/mountpoint-s3/blob/ac6c1770cec5ee7c0fd2ee009b87b9fdddea2af0/doc/TROUBLESHOOTING.md?plain=1#L152-L170).
Currently, it is not possible to pass CLI options using environment variable.

**Comment by dannycjones** [comment]
I'm assuming the problem here is that you cannot use path-style access to the bucket with https://github.com/awslabs/s3-connector-for-pytorch.

Please do [open a feature request](https://github.com/awslabs/s3-connector-for-pytorch/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml) against that repo so that they're aware of the feature request. (I've also let @IsaevIlya know in person!)

Separately, there is a request here is for Mountpoint's S3 client to allow configuration of some of these parameters using environment variables. Unfortunately, I don't think that's a good idea as many are already configured by the application (such as Mountpoint itself) and would be hard to maintain.

I'll close this issue for now since I don't see us adding environment variables as a way to configure client fields like path-style access.
